const actionTypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    RESET_REGISTER: 'RESET_REGISTER', // Add this line

    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_POSTS_ADMIN: 'GET_POSTS_ADMIN',
    GET_NEW_POST: "GET_NEW_POST",
    GET_POST_ID_SUCCESS: "GET_POST_ID_SUCCESS",
    GET_POST_ID_FAIL: "GET_POST_ID_FAIL",
    EDIT_POST: 'EDIT_POST',
    RESET_DATAEDIT_POST: 'RESET_DATAEDIT_POST',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_PROVINCES: 'GET_PROVINCES',

    // USER
    GET_CURRENT: 'GET_CURRENT'


};

export default actionTypes;