const actionTypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    RESET_REGISTER: 'RESET_REGISTER', // Add this line

    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_POSTS_ADMIN: 'GET_POSTS_ADMIN',
    GET_NEW_POST: "GET_NEW_POST",
    GET_OUTSTANDING: "GET_OUTSTANDING",
    GET_POST_ID_FAIL: "GET_POST_ID_FAIL",
    EDIT_POST: 'EDIT_POST',
    RESET_DATAEDIT_POST: 'RESET_DATAEDIT_POST',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_PROVINCES: 'GET_PROVINCES',

    CREATE_APPOINTMENT_SUCCESS: 'CREATE_APPOINTMENT_SUCCESS',
    FETCH_APPOINTMENTS_REQUEST: 'FETCH_APPOINTMENTS_REQUEST',
    FETCH_APPOINTMENTS_FAILURE: 'FETCH_APPOINTMENTS_FAILURE',
    FETCH_APPOINTMENTS_SUCCESS: 'FETCH_APPOINTMENTS_SUCCESS',



    // USER
    GET_CURRENT: 'GET_CURRENT',
    GET_ALL_USER: ' GET_ALL_USER',


};

export default actionTypes;